### ISSUE TITLE
Improve CLI integration

### ISSUE THREAD

**Issue by dkundel** [twilio-labs/svg-to-react#11]
Would you be open for me to rewrite the CLI part of this? I think we could make it a bit more lightweight and more flexible by using I/O streams.

Basically you could use it like this afterwards:

```bash
cat twilio.svg | npx @twilio-labs/svg-to-react --hooks > src/twilio.js
```

While this might look more complicated it would allow people to tightly integrate it into their workflow. Other examples could be:

Convert SVG to component and store it in your clipboard
```bash
cat twilio.svg | svg-to-react | pbcopy
```

Or use the `find` command to find all files in a directory and run them through the tool.

**Comment by TheSisb** [comment]
This sounds awesome.  PRs are always appreciated! :)
