### ISSUE TITLE
Option to export as a named import 

### ISSUE THREAD

**Issue by schrapel** [twilio-labs/svg-to-react#8]
Some people think default exports are bad. It would be nice to have an option that will export as a named function instead.

https://basarat.gitbooks.io/typescript/docs/tips/defaultIsBad.html

**Comment by TheSisb** [comment]
Hey Toby,

The way this library is designed was to allow for maximum freedom with the generated React component.  You should be able to solve your issue using a custom template.  Please see: https://github.com/twilio-labs/svg-to-react#options

You can see an example of our custom template in the Paste design system here: https://github.com/twilio-labs/paste/blob/master/packages/paste-icons/tools/templates/reactIconTemplate.js

Hope this helps!
